name: C++ CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            name: "Linux x64"
            asset_name: "MCRandomProxy-Linux"
          - os: windows-latest
            name: "Windows"
            asset_name: "MCRandomProxy-Windows.exe"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake make

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          echo "Updating MSYS2 packages"
          pacman -Syu --noconfirm
          echo "Installing MinGW and CMake with MSYS2"
          pacman -S --noconfirm mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake
          echo "Adding MinGW bin to PATH"
          echo "C:\\msys64\\mingw64\\bin" >> $GITHUB_PATH
        shell: msys2 {0}


      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: ./build/MCRandomProxy
